crawler:
  allowed_domains:
  - books.toscrape.com
  max_depth: 3
  rate_limit: 1.0
  start_url: http://books.toscrape.com/
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.124 Safari/537.36
extraction_rules:
  availability:
    selector: .product_main .availability
    type: text
  category:
    selector: .breadcrumb li:nth-child(3) a
    type: text
  description:
    selector: null
    type: text
  price:
    selector: .product_main .price_color
    type: text
  rating:
    selector: .product_main .star-rating
    type: text
  title:
    selector: .product_main h1
    type: text
mongodb:
  collection: pages
  database: web_crawler
  uri: mongodb://localhost:27017
rabbitmq:
  host: localhost
  password: guest
  port: 5672
  queue_name: url_queue
  username: guest
