version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  worker:
    build: .
    command: python worker.py
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    deploy:
      replicas: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongodb_data: 